spring.application.name=server
server.port=8080

# PostgreSQL 连接
spring.datasource.url=jdbc:postgresql://localhost:5432/edu_admin
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA 自动建表策略：update 会在启动时自动创建/更新表结构（开发用）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect